In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("data/df_limpio.csv")
df.head()

,ID,Edad,Ingresos,Monto_Inicial,Scoring_Crediticio,Meses_Empleo,Num_Creditos,Ratio_Interes,Duracion,Ratio_Deuda_Ingresos,Estudios,Tipo_Jornada_Laboral,Estado_Civil,Posesion_Hipoteca,Personas_Cargo,Proposito,Fiador,Impago,Prima
0,6B4H6E,22,16000.0,10000,769,22.0,1,8.96,48.0,0.32,Escolar,Desempleado,Soltero,1.0,1.0,Vivienda,0.0,0,65.85
1,VKTUXP,33,38308.0,16474,699,70.0,3,14.07,36.0,0.20,Máster,Jornada completa,Casado,1.0,1.0,Vivienda,0.0,0,260.60
2,5P9OVL,51,51271.0,40770,812,309.0,1,12.66,12.0,0.36,Grado Universitario,Jornada completa,Casado,0.0,1.0,Vivienda,1.0,0,221.02
3,YL0W8G,30,31923.0,36707,813,43.0,1,8.96,24.0,0.32,Grado Universitario,Jornada completa,Casado,0.0,1.0,Vivienda,0.0,0,125.00
4,YP8WTV,28,27373.0,86981,765,60.0,2,10.07,48.0,0.55,Escolar,Jornada completa,Soltero,0.0,1.0,Vivienda,0.0,0,800.00

In [8]:
df.duplicated().sum()

np.int64(0)

In [5]:
df2=pd.read_csv("data/resultado_recomendaciones.csv",sep=";")
df2

            ID Recomendado           Recomendado_Final  Saldo_Impago_Mitad
0       6B4H6E      Aleman                      Aleman             5000.00
1       VKTUXP      Aleman                      Aleman             8237.00
2       5P9OVL     Frances     Frances (ampliar plazo)            21026.59
3       YL0W8G     Frances     Frances (ampliar plazo)            19172.14
4       YP8WTV     Frances  Denegar / estudio especial            47837.16
...        ...         ...                         ...                 ...
101918  5PM51H      Aleman                      Aleman             2840.50
101919  L0RUJT     Frances             Reducir importe            22136.21
101920  8OJZU0     Frances                     Frances            22518.77
101921  II8B24     Frances                     Frances            11434.65
101922  A8KWSO     Frances  Denegar / estudio especial            20642.06

[101923 rows x 4 columns]

In [7]:
df_final = pd.merge(df, df2, on="ID", how="inner")
df_final

,ID,Edad,Ingresos,Monto_Inicial,Scoring_Crediticio,Meses_Empleo,Num_Creditos,Ratio_Interes,Duracion,Ratio_Deuda_Ingresos,...,Estado_Civil,Posesion_Hipoteca,Personas_Cargo,Proposito,Fiador,Impago,Prima,Recomendado,Recomendado_Final,Saldo_Impago_Mitad
0,6B4H6E,22,16000.0,10000,769,22.0,1,8.96,48.0,0.32,...,Soltero,1.0,1.0,Vivienda,0.0,0,65.85,Aleman,Aleman,5000.00
1,VKTUXP,33,38308.0,16474,699,70.0,3,14.07,36.0,0.20,...,Casado,1.0,1.0,Vivienda,0.0,0,260.60,Aleman,Aleman,8237.00
2,5P9OVL,51,51271.0,40770,812,309.0,1,12.66,12.0,0.36,...,Casado,0.0,1.0,Vivienda,1.0,0,221.02,Frances,Frances (ampliar plazo),21026.59
3,YL0W8G,30,31923.0,36707,813,43.0,1,8.96,24.0,0.32,...,Casado,0.0,1.0,Vivienda,0.0,0,125.00,Frances,Frances (ampliar plazo),19172.14
4,YP8WTV,28,27373.0,86981,765,60.0,2,10.07,48.0,0.55,...,Soltero,0.0,1.0,Vivienda,0.0,0,800.00,Frances,Denegar / estudio especial,47837.16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101918,5PM51H,29,35671.0,5681,628,27.0,2,12.11,48.0,0.10,...,Soltero,0.0,1.0,Vivienda,1.0,0,116.89,Aleman,Aleman,2840.50
101919,L0RUJT,28,22864.0,40000,752,9.0,2,10.77,48.0,0.55,...,Casado,0.0,1.0,Vivienda,0.0,0,607.55,Frances,Reducir importe,22136.21
101920,8OJZU0,35,69159.0,41795,699,65.0,2,10.41,36.0,0.29,...,Soltero,0.0,0.0,Vivienda,0.0,0,406.82,Frances,Frances,22518.77
101921,II8B24,39,68375.0,21847,722,170.0,2,6.26,36.0,0.14,...,Casado,0.0,1.0,Vivienda,1.0,0,125.32,Frances,Frances,11434.65
101922,A8KWSO,19,22562.0,40000,779,0.0,1,6.44,24.0,0.55,...,Soltero,0.0,1.0,Vivienda,0.0,0,156.06,Frances,Denegar / estudio especial,20642.06